### ISSUE TITLE
uclibc and musl version of palemoon 27.6.0

### ISSUE THREAD

**Issue by Sharrisii** [Bfgeshka/octopus#10]
Can a uclibc and/or musl version of the palemoon 27.6.0 ebuild be made ?
Some prior work has already been done to try to get palemoon built under uclibc-ng,
and it almost worked. See 
https://forum.palemoon.org/viewtopic.php?t=11951 (continued at topic 13868)
http://forum.palemoon.org/viewtopic.php?t=13898 (page 5)
https://github.com/MoonchildProductions/Pale-Moon/issues/910

Could be especially useful for the Lilblue and Bluedragon gentoo releases (see http://releases.freeharbor.net and http://wiki.gentoo.org/wiki/Project:RelEng_GRS

**Comment by walterdnes** [comment]
Hi; I'm the guy who tried compiling Pale Moon under uclibc-ng. I think uclibc (and the -ng version) is simply too different from glibc for Pale Moon to work without source code changes. libmusl is closer to glibc, and might work, but no guarantees. BTW, Pale Moon is currently at version 27.7.2. I'll raise a separate issue re: keeping up to date with the latest version.

**Comment by Bfgeshka** [comment]
I'll wait for some results and pull requests. Yes, indeed, supporting something aside of usual glibc would be very nice, but it'll require a lot of work.

Firefox code (which is what mostly palemoon consists of) is garbage, in regards of versatility. In other case there wouldn't be so much troubles with compiler support.

**Comment by Sharrisii** [comment]
For updating the pale moon ebuild to version 27.7.2, see the ebuild at
https://github.com/deu/palemoon-overlay/blob/master/www-client/palemoon/palemoon-27.7.2.ebuild

It appears some work has been done on trying to get firefox working on musl:
https://github.com/gentoo/musl/issues/44
Since pale moon is based on firefox 26, it's probably of interest.

Some people have also tried to build palemoon on musl but so far without success; see
https://github.com/MoonchildProductions/Pale-Moon/issues/366
https://forum.voidlinux.eu/t/palemoon-musl-building-fail/3552/10
https://forum.palemoon.org/viewtopic.php?f=61&t=18176
the issues mentioned in that last URL can be resolved by replacing "caddr_t" everywhere by "void *" in the code base.

In addition, I did a few minor changes to the ebuild on my branch (mainly on the IUSE line, for clarity). Can perhaps be changed here as well. 
https://github.com/ecocomputing/TAZ/tree/master/www-client/palemoon

**Comment by Bfgeshka** [comment]
Latest messages in referenced issue are segfault reports, I guess it's not the right time to adopt their work.

Unfortunately I do not have gentoo musl/uclibc setups now (yet), so I cannot work on this issue myself. However, I'm always open for new contributions.

**Comment by anarchpenguin** [comment]
Firefox works fine on musl in gentoo on x86_64. I am currently on 59.0_beta11 which is working without a problem. Palemoon is a waste of time, the code is so out dated and security prone your asking for trouble using it.

**Comment by Sharrisii** [comment]
Source code of palemoon is available via https://www.palemoon.org/sourcecode.shtml
They're currently on 27.7.2
The source code will probably need to be examined first so as to allow 
making either a palemoon version that allows itself to be build with either glibc, uclibc, or musl (depending on what libc is found on the system, ie using a 
if 
then
elif 
then, 
elif 
then 
structure in which it searches for glibc, uclibc-ng, and musl respectively ). Moonchild can then include the code to the sourcecode.
or making a palemoon-uclibc and palemoon-musl version (but the downside then is that with every palemoon update, these separate package needs to be updated separately too) 
or making a uclibc and musl patch that can be applied after building palemoon with glibc or which can be applied to the binary package.
For palemoon musl, perhaps some patches at https://git.alpinelinux.org/cgit/aports/tree/testing/firefox?id=446949693b3878bc159acd9da666fd43c3855d52 can be useful

**Comment by Bfgeshka** [comment]
needs to be reiterated for 28.x
