### ISSUE TITLE
Suggestion: palemoon-bin-9999 ebuild

### ISSUE THREAD

**Issue by walterdnes** [Bfgeshka/octopus#11]
The latest ebuild always seems to be a couple of versions behind the latest Pale Moon version. The current tarballs are...
http://linux.palemoon.org/datastore/release/palemoon-27.7.2.en-US.linux-x86_64.tar.bz2
http://linux.palemoon.org/datastore/release/palemoon-27.7.2.en-US.linux-i686.tar.bz2

Could you do a wildcard wget and extract the tarball, like firefox-bin?  Something like...
/usr/local/bin/wget -r -l1 -np "http://linux.palemoon.org/datastore/release/" -P /tmp -A "palemoon*64.tar.bz2"
/usr/local/bin/wget -r -l1 -np "http://linux.palemoon.org/datastore/release/" -P /tmp -A "palemoon*i686.tar.bz2"

The ebuild would have to figure out whether it's running under 32 or 64 bit Gentoo, and get the appropriate tarball. The advantage of a palemoon-bin-9999 ebuild is that it would always pull down the latest release version, and you would not have to constantly update version numbers.

**Comment by Bfgeshka** [comment]
There is palemoon-9999 if you want latest version available.

This overlay is not targeted for *-bin ebuilds. I can accept pull requests, but I ain't supporting them, since replacing source url won't be enough.

**Comment by l29ah** [comment]
Do you feel it's time to move to https://github.com/MoonchildProductions/UXP/ though?

**Comment by Bfgeshka** [comment]
Probably, but I haven't built onto new repo yet, bet there's plenty of work to do for correct migration. I'll try something this weekend.

If there will be new ebuild fox UXP, beware of profile conversion.

**Comment by l29ah** [comment]
AFAIU, it should be easy to adapt the existing firefox-52 ebuild.

**Comment by Bfgeshka** [comment]
I mean rather that repository-specific paths and configuration options are yet unknown to me.

**Comment by l29ah** [comment]
Okay, #palemoon people have told me they are going to release palemoon-28 ebuild themselves. (layman -a palemoon; strange i don't see it in my eix)

**Comment by Bfgeshka** [comment]
ok then, I'll adapt their ebuild when it comes out.

**Comment by l29ah** [comment]
https://github.com/g4jc/iceweasel-uxp-overlay ok seems like it's already done by a third party.

**Comment by Bfgeshka** [comment]
Stole v28 from deu and rebased 9999 on it.
