### ISSUE TITLE
Pale Moon is missing Inspector

### ISSUE THREAD

**Issue by James-E-A** [Bfgeshka/octopus#2]
Stock Pale Moon has included the web dev tools such as Inspect Element and the JS Debugger since version 27.0.2; however, when installing it from this repo, I have no webdev tools.

And there does not seem to be any USE flag to enable this, either.

The webdev tools are an absolutely vital part of a web browser; please add them back in!

**Comment by Bfgeshka** [comment]
I've got no idea why this part of browser is vital, but there is no need in prebuilt version since for v27 devtools are present as external addon.

https://addons.palemoon.org/extensions/devtools/

**Comment by James-E-A** [comment]
@Bfgeshka The devtools addon is deprecated; it's only "for" Pale Moon versions between versions 27.0.0 and 27.0.2; they are currently being maintained primarily in the mainline browser.

Why not at least add them as a USE flag? _They are included by default in Pale Moon mainline…_

**Comment by James-E-A** [comment]
I just tested out the devtools addon, and it is indeed definitely already suffering from its deprecation. It's much, much less polished than the builtin ones.

**Comment by Bfgeshka** [comment]
AFAIK, devtools addon is not deprecated. And it works for me.

Consider reading ebuilds, you can see that there's no explict devtools disabling.

**Comment by James-E-A** [comment]
@Bfgeshka The official Linux build instructions [specify that dev tools should be enabled during the configuration phase](https://developer.palemoon.org/Developer_Guide:Build_Instructions/Pale_Moon/Linux#head:Mozconfig_Files):

>**Make sure it contains at least the following for a build that is similar to official builds:**
>````
># Please see https://www.palemoon.org/redist.shtml for restrictions when using the official branding.
>ac_add_options --enable-official-branding
>export MOZILLA_OFFICIAL=1
> 
>mk_add_options MOZ_CO_PROJECT=browser
>ac_add_options --enable-application=browser
> 
>mk_add_options MOZ_OBJDIR=/home/$USER/pmbuild/
> 
>ac_add_options --enable-optimize="-O2 -msse2 -mfpmath=sse"
>ac_add_options --with-pthreads
>
>ac_add_options --disable-installer
>ac_add_options --disable-updater
> 
>ac_add_options --enable-release
>ac_add_options --enable-devtools
>ac_add_options --enable-jemalloc
>ac_add_options --enable-shared-js
> 
>ac_add_options --enable-strip
> 
>ac_add_options --x-libraries=/usr/lib
>````

See the `ac_add_options --enable-devtools`? That needs to be exposed via a USE flag, preferably one by default.

Try the devtools addon, and then try the builtin one to compare, if you don't believe me that his abandoned Firebug fork is deprecated.

**Comment by Bfgeshka** [comment]
I don't mind adding new USE sometime later, but I insist that addon is not deprecated.

**Comment by Bfgeshka** [comment]
Created ebuild revision \w devtools USE flag. Try it out for yourself, I haven't any intention to recompile browser only because of this. 

Pretty sure it should work anyway.

**Comment by James-E-A** [comment]
All good; thanks! The builtin devtools' UI is a _lot_ less buggy and unpolished; it's nice to have it on Gentoo.

**Comment by James-E-A** [comment]
Though..why is it disabled by default?

**Comment by Bfgeshka** [comment]
Because it is disabled by default in config.in.
