### ISSUE TITLE
eclass/palemoon-2.eclass:17 won't handle gcc{6,7}

### ISSUE THREAD

**Issue by l29ah** [Bfgeshka/octopus#6]
And https://www.palemoon.org/sourcecode.shtml suggests gcc5 is more stable than the newer ones.

**Comment by Bfgeshka** [comment]
Well, I've planned to mask gcc7 instead of 5. gcc6 works okay so far.

**Comment by l29ah** [comment]
On Fri, Jun 16, 2017 at 06:30:41AM -0700, OMG Eto Zhe BFG wrote:
> Well, I've planned to mask gcc7 instead of 5. gcc6 works okay so far.

It crashes on multiple sites with gcc6 while working fine with 5 for me.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by Bfgeshka** [comment]
It's up to user to decide. gcc7 should be masked because palemoon just cannot be built with it. For other versions warning is enough - gcc6 is not in stable branch and requires manual version change in `gcc-config`, so using it for big and complicated packages should be considered as aknowledged risk.

**Comment by l29ah** [comment]
On Fri, Jun 16, 2017 at 07:01:00AM -0700, OMG Eto Zhe BFG wrote:
> It's up to user to decide. gcc7 should be masked because palemoon just cannot be built with it. For other versions warning is enough - gcc6 is not in stable branch and requires manual version change in `gcc-config`, so using it for big and complicated packages should be considered as aknowledged risk.

Sounds good.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by Bfgeshka** [comment]
new conditions now check and warn if version is more than 5 and drop emerge is it is 7. try it out, looks okay so far.
